package:
  name: cilium-1.14
  version: 1.14.6
  epoch: 0
  description: Cilium is a networking, observability, and security solution with an eBPF-based dataplane
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bpftool
      # cilium does compilations at runtime on the node.
      - clang
      - cni-plugins-loopback
      - iproute2
      - ipset
      - iptables
      - kmod
      - llvm15
      - llvm15-tools
    provides:
      - cilium=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - clang
      - coreutils # for GNU install
      - git
      - go
      - grep
      - iptables # for cilium-iptables
      - llvm15
      - llvm15-tools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cilium/cilium
      tag: v${{package.version}}
      expected-commit: 4a4fa0587d1beb6abce883780957f9848dc50b60

  - uses: patch
    with:
      patches: loopback-location.patch

  - runs: |
      # Remove groupadd from Makefile: it's not doing anything useful in
      # a package build anyway, and it's not available in busybox.
      find . -name Makefile -exec sed -i '/groupadd/d' {} \;

      DESTDIR=${{targets.destdir}} DISABLE_ENVOY_INSTALLATION=1 make build-container
      DESTDIR=${{targets.destdir}} DISABLE_ENVOY_INSTALLATION=1 make install-container

  - uses: strip

subpackages:
  - name: ${{package.name}}-container-init
    description: init scripts for cilium
    dependencies:
      provides:
        - cilium-container-init=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          cp images/cilium/init-container.sh \
             plugins/cilium-cni/install-plugin.sh \
             plugins/cilium-cni/cni-uninstall.sh \
            ${{targets.subpkgdir}}/usr/bin

  - name: ${{package.name}}-container-init-compat
    description: init scripts for cilium
    dependencies:
      runtime:
        - ${{package.name}}-container-init
      provides:
        - cilium-container-init-compat=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}
          ln -sf /usr/bin/init-container.sh ${{targets.subpkgdir}}/init-container.sh
          ln -sf /usr/bin/install-plugin.sh ${{targets.subpkgdir}}/install-plugin.sh
          ln -sf /usr/bin/cni-uninstall.sh ${{targets.subpkgdir}}/cni-uninstall.sh

  - name: ${{package.name}}-iptables
    description: iptables compatibility package for cilium
    dependencies:
      runtime:
        - iptables
      provides:
        - cilium-iptables=${{package.full-version}}
    pipeline:
      - runs: |
          # This script generates a wrapper based on the version
          # of iptables provided by the build environment.
          ./images/runtime/iptables-wrapper-installer.sh
          mkdir -p ${{targets.subpkgdir}}/sbin
          mv /sbin/iptables-wrapper ${{targets.subpkgdir}}/sbin/iptables-wrapper
      - uses: strip

  - name: ${{package.name}}-operator-generic
    description: Generic operator for cilium
    dependencies:
      runtime:
        - gops
      provides:
        - cilium-operator-generic=${{package.full-version}}
    pipeline:
      - runs: |
          cd /home/build/operator
          make cilium-operator-generic
          DESTDIR=${{targets.subpkgdir}} make install-generic
      - uses: strip

  - name: ${{package.name}}-hubble-relay
    description: Hubble relay
    dependencies:
      provides:
        - cilium-hubble-relay=${{package.full-version}}
    pipeline:
      - runs: |
          cd /home/build/hubble-relay
          make hubble-relay
          DESTDIR=${{targets.subpkgdir}} make install
      - uses: strip

test:
  pipeline:
    - runs: cilium version

update:
  # set to false until we figure out whats happening with the latest updates
  enabled: false
  github:
    identifier: cilium/cilium
    strip-prefix: v
    tag-filter-prefix: v1.14.
