package:
  name: libbsd
  version: 0.12.0
  epoch: 0
  description: commonly-used BSD functions not implemented by all libcs
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libmd-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: f741a3bc75162ba19f2f6666076a7961cd75dc93c234e9be4594da1e6f848cfb
      uri: https://libbsd.freedesktop.org/releases/libbsd-${{package.version}}.tar.xz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libbsd-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libmd-dev
        - libbsd
    description: libbsd dev

  - name: libbsd-doc
    pipeline:
      - uses: split/manpages
    description: libbsd manpages

update:
  enabled: true
  release-monitor:
    identifier: 1567
