package:
  name: management-api-for-apache-cassandra
  version: 0.1.73
  epoch: 0
  description: RESTful / Secure Management Sidecar for Apache Cassandra
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - maven
      - openjdk-11
      - openjdk-11-default-jvm

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/k8ssandra/management-api-for-apache-cassandra
      expected-commit: 3055a6d7ec1c33d5d2a311a0767e42780829e2c2
      tag: v${{package.version}}

  - uses: patch
    with:
      patches: upgrade-deps.patch

  - runs: |
      MAAC_PATH="${{targets.destdir}}"/opt/management-api
      mkdir -p "${{targets.destdir}}"/usr/local/bin
      mkdir -p "${{targets.destdir}}"/opt/management-api
      export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
      mvn -q -ff package -DskipTests -DskipOpenApi

      cp ./scripts/docker-entrypoint.sh "${{targets.destdir}}"/usr/local/bin/
      find . -type f -name "datastax-*.jar" -exec mv -t $MAAC_PATH -i '{}' +
      chmod +x "${{targets.destdir}}"/usr/local/bin/docker-entrypoint.sh

subpackages:
  - name: management-api-for-apache-cassandra-compat
    pipeline:
      - runs: |
          ln -s /opt/management-api/datastax-mgmtapi-agent-4.1.x-0.1.0-SNAPSHOT.jar "${{targets.destdir}}"/opt/management-api/datastax-mgmtapi-agent.jar
          ln -s /opt/management-api/datastax-mgmtapi-server-0.1.0-SNAPSHOT.jar "${{targets.destdir}}"/opt/management-api/datastax-mgmtapi-server.jar
          ln -sf /usr/local/bin/docker-entrypoint.sh "${{targets.destdir}}"/docker-entrypoint.sh

update:
  enabled: true
  github:
    identifier: k8ssandra/management-api-for-apache-cassandra
    strip-prefix: v
