package:
  name: npm
  version: 10.4.0
  epoch: 2
  description: "the npm package manager for javascript, mainline"
  copyright:
    - license: Artistic-2.0

environment:
  contents:
    packages:
      - build-base
      - rsync
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://registry.npmjs.org/npm/-/npm-${{package.version}}.tgz
      expected-sha512: 452eccc743957d794e7102d178fb8321874509504f08d6a9587a650cafa687b18374ffd3be8af8a1cbb26d144f4af7dc45bdaf8d126dd5f1c2ab0ddcafca8009
      delete: true

  - uses: patch
    with:
      patches: dont-check-for-last-version.patch

  # Delete the ip package from the npm package to prepare for replacement.
  - working-directory: /home/build/node_modules
    runs: |
      rm -rf ip

  # update the https://www.npmjs.com/package/ip/v/2.0.1
  # that resolves a CVE.
  # remove this once npm fixes it
  - uses: fetch
    working-directory: /home/build/node_modules/ip
    with:
      uri: https://registry.npmjs.org/ip/-/ip-2.0.1.tgz
      expected-sha512: 94950bf6298b4cd8b565f5d3f8353aac105d6e228606e6b2f41eb11923d58d4790c1a1f54481aa79ff1166452d1e2a0b9923693d1e4ce0754a2469b58fc15655
      delete: true

  - runs: |
      # Wrapper scripts written in Bash and CMD.
      rm bin/npm bin/npx bin/*.cmd
      rm README.md

      # HTML docs
      rm -rf docs

  - working-directory: /home/build/node_modules
    runs: |
      find . -type f \( \
             -name '.*' -o \
             -name '*.cmd' -o \
             -name '*.bat' -o \
             -name '*.map' -o \
             -name '*.md' -o \
             \( -name '*.ts' -a ! -name '*.d.ts' \) -o \
             -name 'AUTHORS*' -o \
             -name 'LICENSE*' -o \
             -name 'license' -o \
             -name 'node-gyp' -o \
             -name 'Makefile' -o \
             -name 'README*' -o \
             -name 'readme.markdown' \) -delete

      rm -rf ./*/.git* ./*/doc ./*/docs ./*/examples ./*/scripts ./*/test
      rm -rf node_modules/node-gyp

      find . -type f -executable  -exec chmod -x {} \;

  - working-directory: /home/build/man
    runs: |
      for f in man5/folders.5 man5/install.5 man7/*.7; do
        sec=${f##*.}
        name=$(basename $f .$sec)
        title=$(echo "$name" | tr '[:lower:]' '[:upper:]')

        sed -Ei "s/^\.TH \"$title\"/.TH \"NPM-$title\"/" "$f"
        mv "$f" "${f%/*}/npm-$name.$sec"
      done

  - runs: |
      destdir="${{targets.destdir}}"/usr/lib/node_modules/npm
      install -dDm755 "$destdir"
      rsync -av --exclude melange-out /home/build/ "$destdir"
      chmod 755 "$destdir"

  - working-directory: ${{targets.destdir}}/usr/bin
    runs: |
      ln -s ../lib/node_modules/npm/bin/npm-cli.js npm
      ln -s ../lib/node_modules/npm/bin/npx-cli.js npx

  - working-directory: ${{targets.destdir}}/usr/share
    runs: |
      mv "${{targets.destdir}}"/usr/lib/node_modules/npm/man man
      ln -s ../../../share/man "${{targets.destdir}}"/usr/lib/node_modules/npm/man

subpackages:
  - name: "npm-doc"
    description: "npm documentation"
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  ignore-regex-patterns:
    - -v # ignore versions that start contain a -v, e.g. arborist-v7.2.1, libnpmfund-v4.2.0
  github:
    identifier: npm/cli
    strip-prefix: v
    tag-filter: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - nodejs
    environment:
      HOME: /home/build
  pipeline:
    - runs: |
        npm --version
        npm install -g cowsay
        cowsay Yay! It works!
