package:
  name: openjpeg
  version: 2.5.0
  epoch: 1
  description: "Open-source implementation of JPEG2000 image codec"
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - doxygen
      - lcms2-dev
      - libpng-dev
      - samurai
      - tiff-dev
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/uclouvain/openjpeg/archive/v${{package.version}}/openjpeg-v${{package.version}}.tar.gz
      expected-sha512: 08975a2dd79f1e29fd1824249a5fbe66026640ed787b3a3aa8807c2c69f994240ff33e2132f8bf15bbc2202bef7001f98e42d487231d4eebc8e503538658049a

  # - uses: patch
  #   with:
  #     patches: fix-cmakelists.patch
  - uses: cmake/configure
    with:
      opt: |
        -G Ninja \
        -DCMAKE_BUILD_TYPE=MinSizeRel \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DOPENJPEG_INSTALL_LIB_DIR=lib

  - uses: cmake/build

  - uses: cmake/install

subpackages:
  - name: "openjpeg-dev"
    description: "headers for openjpeg"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - openjpeg

  - name: openjpeg-tools
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/bin/ ${{targets.subpkgdir}}/usr/bin/
    description: openjpeg (development tools)

update:
  enabled: true
  release-monitor:
    identifier: 2550
