package:
  name: py3-gast
  version: 0.5.4
  epoch: 3
  description: Python AST that abstracts the underlying Python version
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/serge-sans-paille/gast
      tag: ${{package.version}}
      expected-commit: 1f872364a9964bdb739c4f76d0be463104cc4757

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: serge-sans-paille/gast
    use-tag: true
