package:
  name: terraform-docs
  version: 0.17.0
  epoch: 0
  description: Generate documentation from Terraform modules in various output formats
  copyright:
    - license: MIT

pipeline:
  - uses: go/install
    with:
      package: github.com/terraform-docs/terraform-docs
      version: v${{package.version}}

test:
  pipeline:
    - runs: terraform-docs --help

update:
  enabled: true
  github:
    identifier: terraform-docs/terraform-docs
    strip-prefix: v
    tag-filter: v
