package:
  name: xterm
  version: "390"
  epoch: 0
  description: X Terminal Emulator
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - freetype
      - freetype-dev
      - libice-dev
      - libutempter-dev
      - libx11-dev
      - libxaw-dev
      - libxft-dev
      - libxkbfile-dev
      - libxmu-dev
      - libxt-dev
      - luit-dev
      - ncurses-dev
      - ncurses-terminfo-base
      - pcre2-dev
      - utmps-dev
      - xbitmaps-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 75117c3cc5174a09c425ef106e69404d72f5ef05e03a5da00aaf15792d6f9c0f
      uri: https://invisible-island.net/archives/xterm/xterm-${{package.version}}.tgz

  - uses: autoconf/configure
    with:
      opts: |
        --with-x \
        --disable-full-tgetent \
        --disable-imake \
        --enable-ansi-color \
        --enable-88-color \
        --enable-256-color \
        --enable-broken-osc \
        --enable-broken-st \
        --enable-load-vt-fonts \
        --enable-i18n \
        --enable-wide-chars \
        --enable-doublechars \
        --enable-warnings \
        --enable-tcap-query \
        --enable-logging \
        --enable-dabbrev \
        --enable-freetype \
        --enable-luit \
        --enable-mini-luit \
        --enable-narrowproto \
        --enable-exec-xterm \
        --enable-sixel-graphics \
        --with-tty-group=tty \
        --with-utempter \
        --with-pcre2

  - uses: autoconf/make

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin
      make DESTDIR="${{targets.destdir}}" install
      builddir=$(pwd)
      install -m755 -d "${{targets.destdir}}"/usr/share/applications
      install -m644 "$builddir"/xterm.desktop "${{targets.destdir}}"/usr/share/applications/
      install -m644 "$builddir"/uxterm.desktop "${{targets.destdir}}"/usr/share/applications/

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 5272
